base:
  title: "人脸识别"
  description: "人脸识别服务，包含人脸库注册，删除人脸"
  version: "1.0rc"
  db_url: "sqlite://models/DB.sqlite"
  debug: true
  allow_origins:
    - "*"
  allow_methods:
    - "*"
  allow_headers:
    - "*"
  port: 9026
  workers: 1

face:
  rec_threshold: 0.7
  is_anti_spoof: false
  use_gpu: false
  gpu_id: 0
  cuda_dir: ""
  tracking_size: [ 310,310 ]
  functions:
    # all data in ["FACE_DETECT","LANDMARKER5","LIVENESS","LANDMARKER_MASK","FACE_AGE",
    #  "FACE_GENDER","FACE_RECOGNITION","MOUTH_MASK","EYE_STATE","FACE_CLARITY",
    #  "FACE_BRIGHT","FACE_RESOLUTION","FACE_POSE","FACE_INTEGRITY","FACE_TRACK"]
    - "FACE_DETECT"
    - "LANDMARKER5"
    - "LIVENESS"
    - "FACE_RECOGNITION"
    - "EYE_STATE"
    - "FACE_CLARITY"
    - "FACE_BRIGHT"
    - "FACE_RESOLUTION"
    - "FACE_INTEGRITY"
  allow_images: [ "jpg", "jpeg", "png", "bmp" ]
